name: udara_cli
description: A command-line tool for managing Udara project builds.
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.5.0
  process_run: ^1.2.4
  yaml: ^3.1.2
  http:

executables:
  udara_cli:
