/// Generates the Dart class that carries a client's configuration in
/// `generated` mode. Pure: all inputs are passed in, so it is easy to test.
///
/// The class mirrors flutter_dotenv's API (`env`, `get`, `maybeGet`,
/// `getInt`, `getDouble`, `getBool`, `isEveryDefined`, `isInitialized`) so
/// migrating code is a rename, and adds a typed constant per key.
///
/// Its shape must be identical for every client, or code that compiles for
/// one client would fail for another. So fields are generated for the union
/// of keys across all clients' env files; a key missing from any of them is
/// a nullable `String?`, and a key every client defines is a `String`.
class AppConfigGenerator {
  const AppConfigGenerator._();

  static String generate({
    required String className,
    required String client,
    required bool isTest,
    required String sourceFile,
    required Map<String, String> values,
    required Set<String> allKeys,
    required Set<String> alwaysPresent,
  }) {
    final keys = allKeys.toList()..sort();
    final names = fieldNames(keys);
    final out = StringBuffer()
      ..writeln(
          '// GENERATED BY udara_cli from $sourceFile. DO NOT EDIT BY HAND.')
      ..writeln('//')
      ..writeln(
          '// Regenerated for each client by `udara_cli build` and `whitelabel`, and')
      ..writeln(
          '// restored afterwards. Everything in this file ships inside the app and')
      ..writeln('// can be read by anyone who inspects it: keep secrets in')
      ..writeln(
          '// clients/<client>/.secrets, which udara_cli never compiles in.')
      ..writeln('//')
      ..writeln('// ignore_for_file: type=lint, constant_identifier_names')
      ..writeln()
      ..writeln('/// Configuration of the client this app was built for.')
      ..writeln('class $className {')
      ..writeln('  $className._();')
      ..writeln()
      ..writeln('  /// The client this build was generated for.')
      ..writeln('  static const String client = ${_literal(client)};')
      ..writeln()
      ..writeln('  /// Whether the test environment (.env_test) was used.')
      ..writeln('  static const bool isTestEnvironment = $isTest;')
      ..writeln();

    for (final key in keys) {
      final name = names[key]!;
      final value = values[key];
      final type = alwaysPresent.contains(key) ? 'String' : 'String?';
      out
        ..writeln(
            '  /// `$key`${alwaysPresent.contains(key) ? '' : ' (not defined by every client)'}')
        ..writeln(
            '  static const $type $name = ${value == null ? 'null' : _literal(value)};');
    }

    out
      ..writeln()
      ..writeln(
          '  /// Every value by its .env key, like flutter_dotenv\'s `dotenv.env`.')
      ..writeln('  static const Map<String, String> env = {');
    for (final key in keys.where(values.containsKey)) {
      out.writeln('    ${_literal(key)}: ${_literal(values[key]!)},');
    }
    out
      ..writeln('  };')
      ..writeln()
      ..writeln(
          '  /// Always true: the values are compiled in, nothing needs loading.')
      ..writeln('  static const bool isInitialized = true;')
      ..writeln()
      ..write(_helpers);
    out.writeln('}');
    return out.toString();
  }

  static const _helpers =
      r'''  /// The value of [name]; throws if it is missing and no [fallback] is given.
  static String get(String name, {String? fallback}) {
    final value = env[name] ?? fallback;
    if (value == null) {
      throw AssertionError(
          '$name variable not found. A non-null fallback is required for missing entries');
    }
    return value;
  }

  /// The value of [name], or [fallback] (null by default) when it is missing.
  static String? maybeGet(String name, {String? fallback}) => env[name] ?? fallback;

  static int getInt(String name, {int? fallback}) {
    final value = maybeGet(name);
    if (value == null) return _required(name, fallback);
    return int.parse(value);
  }

  static double getDouble(String name, {double? fallback}) {
    final value = maybeGet(name);
    if (value == null) return _required(name, fallback);
    return double.parse(value);
  }

  /// Accepts true/false and 1/0, like flutter_dotenv.
  static bool getBool(String name, {bool? fallback}) {
    final value = maybeGet(name);
    if (value == null) return _required(name, fallback);
    switch (value.toLowerCase()) {
      case 'true':
      case '1':
        return true;
      case 'false':
      case '0':
        return false;
    }
    throw FormatException('Could not parse "$value" as a bool', name);
  }

  static bool isEveryDefined(Iterable<String> names) =>
      names.every((name) => env[name]?.isNotEmpty ?? false);

  static T _required<T>(String name, T? fallback) {
    if (fallback == null) {
      throw AssertionError(
          '$name variable not found. A non-null fallback is required for missing entries');
    }
    return fallback;
  }
''';

  static const _reserved = {
    // Dart reserved words and built-in identifiers.
    'abstract', 'as', 'assert', 'async', 'await', 'base', 'break', 'case',
    'catch', 'class',
    'const', 'continue', 'covariant', 'default', 'deferred', 'do', 'dynamic',
    'else', 'enum',
    'export', 'extends', 'extension', 'external', 'factory', 'false', 'final',
    'finally', 'for',
    'function', 'get', 'hide', 'if', 'implements', 'import', 'in', 'interface',
    'is', 'late',
    'library', 'mixin', 'new', 'null', 'of', 'on', 'operator', 'part',
    'required', 'rethrow',
    'return', 'sealed', 'set', 'show', 'static', 'super', 'switch', 'sync',
    'this', 'throw',
    'true', 'try', 'type', 'typedef', 'var', 'void', 'when', 'while', 'with',
    'yield',
    // Members of the generated class and Object.
    'client', 'isTestEnvironment', 'env', 'isInitialized', 'maybeGet', 'getInt',
    'getDouble',
    'getBool', 'isEveryDefined', 'hashCode', 'runtimeType', 'toString',
    'noSuchMethod',
  };

  /// Maps each key to a unique, stable Dart field name: `PRIMARY_COLOR` ->
  /// `primaryColor`. Deterministic for a sorted key list, so every client's
  /// class gets the same names.
  static Map<String, String> fieldNames(List<String> sortedKeys) {
    final taken = <String>{};
    final result = <String, String>{};
    for (final key in sortedKeys) {
      final words = key
          .split(RegExp(r'[^A-Za-z0-9]+'))
          .where((w) => w.isNotEmpty)
          .toList();
      var name = words.isEmpty
          ? 'value'
          : words.first.toLowerCase() +
              words
                  .skip(1)
                  .map((w) => w[0].toUpperCase() + w.substring(1).toLowerCase())
                  .join();
      if (RegExp(r'^[0-9]').hasMatch(name)) name = 'k$name';
      if (_reserved.contains(name)) name = '${name}Value';
      var unique = name;
      for (var i = 2; taken.contains(unique); i++) {
        unique = '$name$i';
      }
      taken.add(unique);
      result[key] = unique;
    }
    return result;
  }

  /// A single-quoted Dart string literal with everything escaped, including
  /// `$` so values are never interpolated.
  static String _literal(String value) {
    final b = StringBuffer("'");
    for (final rune in value.runes) {
      switch (rune) {
        case 0x5C:
          b.write(r'\\');
        case 0x27:
          b.write(r"\'");
        case 0x24:
          b.write(r'\$');
        case 0x0A:
          b.write(r'\n');
        case 0x0D:
          b.write(r'\r');
        case 0x09:
          b.write(r'\t');
        default:
          if (rune < 0x20 || rune == 0x7F) {
            b.write('\\u{${rune.toRadixString(16)}}');
          } else {
            b.writeCharCode(rune);
          }
      }
    }
    b.write("'");
    return b.toString();
  }
}
