import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

/// Text embedded in generated placeholder images so `doctor` can tell a
/// template image from a real one.
const placeholderPngComment = 'udara_cli placeholder';

/// Builds a valid solid-colour PNG so icon and splash tooling can run
/// before a client has real artwork. [size] is the width and height.
Uint8List buildPlaceholderPng({
  int size = 512,
  int red = 0x42,
  int green = 0x85,
  int blue = 0xF4,
}) {
  final raw = BytesBuilder();
  final row = Uint8List(1 + size * 3);
  for (var x = 0; x < size; x++) {
    row[1 + x * 3] = red;
    row[2 + x * 3] = green;
    row[3 + x * 3] = blue;
  }
  for (var y = 0; y < size; y++) {
    raw.add(row);
  }
  final compressed = ZLibEncoder().convert(raw.takeBytes());

  final ihdr = ByteData(13)
    ..setUint32(0, size)
    ..setUint32(4, size)
    ..setUint8(8, 8) // bit depth
    ..setUint8(9, 2) // colour type: truecolour
    ..setUint8(10, 0)
    ..setUint8(11, 0)
    ..setUint8(12, 0);

  final text = utf8.encode('Comment\u0000$placeholderPngComment');

  final png = BytesBuilder()
    ..add(const [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A])
    ..add(_chunk('IHDR', ihdr.buffer.asUint8List()))
    ..add(_chunk('tEXt', Uint8List.fromList(text)))
    ..add(_chunk('IDAT', Uint8List.fromList(compressed)))
    ..add(_chunk('IEND', Uint8List(0)));
  return png.takeBytes();
}

/// Whether [file] is a placeholder generated by [buildPlaceholderPng].
bool isPlaceholderPng(File file) {
  try {
    final bytes = file.readAsBytesSync();
    if (bytes.length > 64 * 1024) return false;
    return latin1
        .decode(bytes, allowInvalid: true)
        .contains(placeholderPngComment);
  } catch (_) {
    return false;
  }
}

Uint8List _chunk(String type, Uint8List data) {
  final typeBytes = ascii.encode(type);
  final out = ByteData(12 + data.length);
  out.setUint32(0, data.length);
  final body = Uint8List.fromList([...typeBytes, ...data]);
  out.buffer.asUint8List().setRange(4, 8 + data.length, body);
  out.setUint32(8 + data.length, _crc32(body));
  return out.buffer.asUint8List();
}

final _crcTable = List<int>.generate(256, (n) {
  var c = n;
  for (var k = 0; k < 8; k++) {
    c = (c & 1) != 0 ? 0xEDB88320 ^ (c >> 1) : c >> 1;
  }
  return c;
});

int _crc32(Uint8List bytes) {
  var crc = 0xFFFFFFFF;
  for (final b in bytes) {
    crc = _crcTable[(crc ^ b) & 0xFF] ^ (crc >> 8);
  }
  return (crc ^ 0xFFFFFFFF) & 0xFFFFFFFF;
}
