import '../core/core.dart';

class CleanCommand extends UdaraCommand {
  CleanCommand() {
    argParser.addFlag(
      'workspaces',
      negatable: false,
      help: 'Only delete this project\'s parallel build workspaces '
          '(~/.udara_cli/workspaces/) to free disk space.',
    );
  }

  @override
  final name = 'clean';
  @override
  final description = '''Restore the project state and run `flutter clean`.

Restores any files backed up by an interrupted build, removes branding
folders generated by udara_cli, puts the original fonts back, and finally
runs `flutter clean`. Safe to run at any time.

With --workspaces, only deletes the copies of this project that parallel
builds use. They are recreated (and re-cached) on the next parallel build.''';

  @override
  Future<void> run() async {
    if (argResults!['workspaces'] as bool) {
      final workspaces = WorkspaceManager(projectDir);
      final path = workspaces.root.path;
      if (await workspaces.removeAll()) {
        Logger.success('Deleted parallel build workspaces at $path');
      } else {
        Logger.info('No parallel build workspaces for this project.');
      }
      return;
    }

    final config = ConfigService(projectDir);
    final cleanup = CleanupService(projectDir: projectDir, config: config);

    Logger.phase('Restoring Project State');
    await cleanup.performFullCleanup();

    // After `whitelabel --keep`, the generated config still holds that
    // client's values; put the default client's back.
    final appConfig = AppConfigService(projectDir, config);
    // A root .env left by an earlier run (e.g. before this project moved to
    // generated config) is only udara_cli's staging: remove it.
    if (appConfig.settings.isGenerated && appConfig.isStagedRootEnv()) {
      await File('$projectDir/.env').delete();
      Logger.info(
          'Removed the root .env udara_cli had staged (not needed in generated mode).');
    }
    final defaultEnv =
        File('${clientsDir.path}/${WhiteLabelService.defaultClientName}/.env');
    if (appConfig.settings.isGenerated && defaultEnv.existsSync()) {
      await appConfig.write(
          client: WhiteLabelService.defaultClientName,
          envFile: defaultEnv,
          isTest: false,
          trackForCleanup: false);
      Logger.info(
          'Regenerated ${appConfig.settings.output} for the default client.');
    }

    Logger.phase('Flutter Clean');
    await runShell('flutter clean');
    Logger.success('Project cleaned successfully.');
  }
}
