import '../core/core.dart';

class CleanCommand extends UdaraCommand {
  @override
  final name = 'clean';
  @override
  final description = '''Restore the project state and run `flutter clean`.

Restores any files backed up by an interrupted build, removes branding
folders generated by udara_cli, puts the original fonts back, and finally
runs `flutter clean`. Safe to run at any time.''';

  @override
  Future<void> run() async {
    final config = ConfigService(projectDir);
    final cleanup = CleanupService(projectDir: projectDir, config: config);

    Logger.phase('Restoring Project State');
    await cleanup.performFullCleanup();

    Logger.phase('Flutter Clean');
    await runShell('flutter clean');
    Logger.success('Project cleaned successfully.');
  }
}
