import 'dart:convert';

import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';
import 'package:yaml_edit/yaml_edit.dart';

import '../core/core.dart';

class CleanCommand extends UdaraCommand {
  CleanCommand() {
    argParser.addFlag(
      'workspaces',
      negatable: false,
      help: 'Only delete this project\'s parallel build workspaces '
          '(~/.udara_cli/workspaces/) to free disk space.',
    );
  }

  @override
  final name = 'clean';
  @override
  final description = '''Restore the project state and run `flutter clean`.

Undoes "whitelabel --keep" (the editors' Run Client) and interrupted builds:
restores the pubspec, fonts, generated config, launcher/splash config and
native branding from the backups they left, removes branding folders
generated by udara_cli, and finally runs `flutter clean`. Safe to run at any
time.

With --workspaces, only deletes the copies of this project that parallel
builds use. They are recreated (and re-cached) on the next parallel build.''';

  @override
  Future<void> run() async {
    if (argResults!['workspaces'] as bool) {
      final workspaces = WorkspaceManager(projectDir);
      final path = workspaces.root.path;
      if (await workspaces.removeAll()) {
        Logger.success('Deleted parallel build workspaces at $path');
      } else {
        Logger.info('No parallel build workspaces for this project.');
      }
      return;
    }

    final config = ConfigService(projectDir);
    final cleanup = CleanupService(projectDir: projectDir, config: config);

    Logger.phase('Restoring Project State');
    final hadBackups = Directory(p.join(projectDir, '.udara')).existsSync();
    final kept = config.keptClient();
    if (kept != null) {
      Logger.info('Undoing "whitelabel --keep" for "$kept"...');
    }
    await cleanup.performFullCleanup();

    // Projects branded with --keep before udara_cli 1.3.1 have no backups
    // to restore from; repair the sections udara_cli manages from the last
    // commit instead.
    if (!hadBackups) _repairManagedSectionsFromLastCommit();

    final appConfig = AppConfigService(projectDir, config);
    // A root .env left by an earlier run (e.g. before this project moved to
    // generated config) is only udara_cli's staging: remove it.
    if (appConfig.settings.isGenerated && appConfig.isStagedRootEnv()) {
      await File('$projectDir/.env').delete();
      Logger.info(
          'Removed the root .env udara_cli had staged (not needed in generated mode).');
    }
    final defaultEnv =
        File('${clientsDir.path}/${WhiteLabelService.defaultClientName}/.env');
    if (appConfig.settings.isGenerated && defaultEnv.existsSync()) {
      await appConfig.write(
          client: WhiteLabelService.defaultClientName,
          envFile: defaultEnv,
          isTest: false,
          trackForCleanup: false);
      Logger.info(
          'Regenerated ${appConfig.settings.output} for the default client.');
    }

    Logger.phase('Flutter Clean');
    await runShell('flutter clean');
    Logger.success('Project cleaned successfully.');
  }

  /// Puts back the pubspec `fonts:` section, the branding asset entry and
  /// the splash image, and the launcher icon path, as they are in the last
  /// commit, when they differ. Nothing else in the files is touched.
  void _repairManagedSectionsFromLastCommit() {
    String? committed(String rel) {
      try {
        final r = Process.runSync('git', ['show', 'HEAD:$rel'],
            workingDirectory: projectDir);
        return r.exitCode == 0 ? '${r.stdout}' : null;
      } catch (_) {
        return null; // git not installed
      }
    }

    bool same(Object? a, Object? b) => jsonEncode(a) == jsonEncode(b);

    final pubspecFile = File(p.join(projectDir, 'pubspec.yaml'));
    final committedPubspec = committed('pubspec.yaml');
    if (pubspecFile.existsSync() && committedPubspec != null) {
      final current = pubspecFile.readAsStringSync();
      final now = loadYaml(current);
      final head = loadYaml(committedPubspec);
      final editor = YamlEditor(current);
      final repaired = <String>[];

      final headFonts = (head is YamlMap ? head['flutter'] : null) is YamlMap
          ? head['flutter']['fonts']
          : null;
      final nowFonts = (now is YamlMap ? now['flutter'] : null) is YamlMap
          ? now['flutter']['fonts']
          : null;
      if (!same(headFonts, nowFonts)) {
        if (headFonts == null) {
          editor.remove(['flutter', 'fonts']);
        } else {
          editor.update(['flutter', 'fonts'], headFonts);
        }
        repaired.add('fonts');
      }

      List<String> assetsOf(Object? yaml) =>
          ((yaml is YamlMap && yaml['flutter'] is YamlMap)
                  ? yaml['flutter']['assets'] as YamlList?
                  : null)
              ?.map((a) => '$a')
              .toList() ??
          <String>[];
      bool isBranding(String a) => a.startsWith('assets/branding/');
      final nowAssets = assetsOf(now);
      final headBranding = assetsOf(head).where(isBranding).toList();
      final nowBranding = nowAssets.where(isBranding).toList();
      if (!same(headBranding, nowBranding) && nowAssets.isNotEmpty) {
        editor.update(['flutter', 'assets'],
            [...nowAssets.where((a) => !isBranding(a)), ...headBranding]);
        repaired.add('branding asset entry');
      }

      final headSplash = head is YamlMap && head['splash_master'] is YamlMap
          ? head['splash_master']['image']
          : null;
      final nowSplash = now is YamlMap && now['splash_master'] is YamlMap
          ? now['splash_master']['image']
          : null;
      if (headSplash != null && headSplash != nowSplash) {
        editor.update(['splash_master', 'image'], headSplash);
        repaired.add('splash image');
      }

      if (repaired.isNotEmpty) {
        pubspecFile.writeAsStringSync(editor.toString());
        Logger.info(
            'pubspec.yaml: restored the ${repaired.join(', ')} from the last commit.');
      }
    }

    final iconsFile = File(p.join(projectDir, 'flutter_launcher_icons.yaml'));
    final committedIcons = committed('flutter_launcher_icons.yaml');
    if (iconsFile.existsSync() && committedIcons != null) {
      final head = loadYaml(committedIcons);
      final current = iconsFile.readAsStringSync();
      final now = loadYaml(current);
      final headPath =
          head is YamlMap && head['flutter_launcher_icons'] is YamlMap
              ? head['flutter_launcher_icons']['image_path']
              : null;
      final nowPath = now is YamlMap && now['flutter_launcher_icons'] is YamlMap
          ? now['flutter_launcher_icons']['image_path']
          : null;
      if (headPath != null && headPath != nowPath) {
        final editor = YamlEditor(current)
          ..update(['flutter_launcher_icons', 'image_path'], headPath);
        iconsFile.writeAsStringSync(editor.toString());
        Logger.info(
            'flutter_launcher_icons.yaml: restored the icon path from the last commit.');
      }
    }
  }
}
